### ISSUE TITLE
onStepEnter fails with Chrome on specific screen size

### ISSUE THREAD

**Issue by maxdulieu** [russellgoldenberg/scrollama#93] opened 2019-08-02 13:52 UTC
I have noticed this weird behavior when using scrollama on my laptop vs. my desktop, onStepEnter would only be triggered at around 0.8 progress and go straight to 100%. I use Chrome 76.0.3809.87. 

It gets solve when I zoom in and out of my browser. 

Let me know if you need more info

![scrollama](https://user-images.githubusercontent.com/25515702/62374840-d804bb80-b50a-11e9-86d2-d32fe5554eb0.PNG)

**Comment by maxdulieu** [comment] 2019-08-02 14:11
I was able to reproduce this behavior by zooming on my desktop to 150%

**Comment by stassribnyi** [comment] 2019-08-07 08:46
Same issue here, I recently updated my app to use scrollama.js instead of waypoint.js to improve performance and encountered this issue on my smartphone (Huawei P10). 

BTW, it is also reproducible on Chrome with 150% as mentioned above by @maxdulieu.

**Comment by stassribnyi** [comment] 2019-08-07 09:45
Possibly duplicate of "Offset trigger not working properly on Chrome mobile."  #87

**Comment by pldg** [comment] 2019-08-08 09:30
Another possible duplicate https://github.com/russellgoldenberg/scrollama/issues/64

**Comment by russellgoldenberg** [comment] 2020-02-14 13:21
If this is a zoom issue, that is a duplicate (as @pldg mentioned) of #64. If you can paste the code that would be helpful to try and reproduce.

**Comment by architchandra** [comment] 2021-04-02 16:17
I'm facing the same issue. One of the elements that we're using to trigger changes in the background colour does not get registered when it crosses the threshold level (have noticed this more often on a laptop both with and without an external monitor). 

A few interesting observations:
- It's always the same element that does not get registered
- This happens only when I scroll up from the bottom of the page
- This happens only when I scroll really slowly (easier to reproduce using a trackpad compared to a mouse scroll wheel)
- This happens only above a certain viewport width, at least if an external monitor is connected (specifically, < 1388px)

Please let me know if anyone has ideas on how to work around this problem.

**Closed** 2022-04-02 00:02 UTC
Labels: duplicate, needs more info, wontfix, 2.0
